version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: "@storybook/addons"
    versions:
    - 6.2.2
    - 6.2.7
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.3
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
    - 7.13.14
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.21
    - 6.2.2
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.2.2
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: nested-object-assign
    versions:
    - 1.0.4
  - dependency-name: mixin-deep
    versions:
    - 1.3.2
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: acorn
    versions:
    - 5.7.4
